"""added Permission table

Revision ID: aefdca9d0b9f
Revises: c40be61cfcb3
Create Date: 2025-08-01 11:57:05.037319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefdca9d0b9f'
down_revision: Union[str, None] = 'c40be61cfcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=32), nullable=False),
    sa.Column('permission_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_accessed_at')
    op.drop_table('permissions')
    # ### end Alembic commands ###
