"""Roles table data generated from env file

Revision ID: c94fafdcd85a
Revises: 7fd02218a27e
Create Date: 2025-08-13 10:07:38.562472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94fafdcd85a'
down_revision: Union[str, None] = '7fd02218a27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import os
    import json
    from dotenv import load_dotenv

    # load env vars
    load_dotenv()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission')
    op.drop_table('users_roles')
    op.drop_table('users_permissions')
    # ### end Alembic commands ###

    # Clear existing data
    op.execute("DELETE FROM roles")

    # Get mapped roles
    roles_env = os.getenv('ROLES')
    if roles_env:
        try:
            roles_data = json.loads(roles_env)

            for role_key, role_info in roles_data.items():
                discord_id = role_info.get('discord_id', '')
                name = role_info.get('name', role_key)
                description = role_info.get('description', f'{name} role')
                
                # Use string formatting for Alembic op.execute
                sql = f"""INSERT INTO roles (role_discord_id, role_name, role_description, created_at, updated_at) 
                         VALUES ('{discord_id}', '{name}', '{description}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"""
                op.execute(sql)
                print(f"Inserted role: {name}")
        except json.JSONDecodeError as e:
            print(f"Error parsing ROLES env; {e}")
        except Exception as e:
            print(f"Error inserting roles: {e}")
            raise
    else:
        print("No ROLES found in env")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_permissions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name='users_permissions_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_permissions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name='users_permissions_pkey')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='users_roles_role_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_roles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='users_roles_pkey')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name='role_permission_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='role_permission_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permission_pkey')
    )
    # ### end Alembic commands ###
